import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, cpSync } from 'node:fs'
import { join, basename } from 'node:path'

interface PackageJson {
  name?: string
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
}

function detectPackageManager(cwd: string): 'pnpm' | 'yarn' | 'bun' | 'npx' {
  if (existsSync(join(cwd, 'pnpm-lock.yaml'))) return 'pnpm'
  if (existsSync(join(cwd, 'yarn.lock'))) return 'yarn'
  if (existsSync(join(cwd, 'bun.lockb'))) return 'bun'
  return 'npx'
}

function getMcpCommand(pm: 'pnpm' | 'yarn' | 'bun' | 'npx'): { command: string; args: string[] } {
  const cliPath = 'node_modules/@rudderjs/cli/src/index.ts'

  switch (pm) {
    case 'pnpm':
      return { command: 'pnpm', args: ['exec', 'tsx', cliPath, 'boost:mcp'] }
    case 'yarn':
      return { command: 'yarn', args: ['tsx', cliPath, 'boost:mcp'] }
    case 'bun':
      return { command: 'bunx', args: ['tsx', cliPath, 'boost:mcp'] }
    default:
      return { command: 'npx', args: ['tsx', cliPath, 'boost:mcp'] }
  }
}

function findRudderPackages(cwd: string): string[] {
  const pkgJsonPath = join(cwd, 'package.json')
  if (!existsSync(pkgJsonPath)) return []

  const raw = readFileSync(pkgJsonPath, 'utf-8')
  const pkg: PackageJson = JSON.parse(raw) as PackageJson
  const allDeps = { ...pkg.dependencies, ...pkg.devDependencies }

  return Object.keys(allDeps).filter((name) => name.startsWith('@rudderjs/'))
}

interface PackageGuideline {
  packageName: string
  shortName: string
  content: string
}

function collectGuidelines(cwd: string, packages: string[]): PackageGuideline[] {
  const results: PackageGuideline[] = []

  for (const pkg of packages) {
    const guidelinePath = join(cwd, 'node_modules', pkg, 'boost', 'guidelines.md')
    if (existsSync(guidelinePath)) {
      results.push({
        packageName: pkg,
        shortName: pkg.replace('@rudderjs/', ''),
        content: readFileSync(guidelinePath, 'utf-8'),
      })
    }
  }

  return results
}

interface PackageSkill {
  packageName: string
  skillName: string
  sourcePath: string
}

function collectSkills(cwd: string, packages: string[]): PackageSkill[] {
  const results: PackageSkill[] = []

  for (const pkg of packages) {
    const skillsDir = join(cwd, 'node_modules', pkg, 'boost', 'skills')
    if (!existsSync(skillsDir)) continue

    try {
      const entries = readdirSync(skillsDir, { withFileTypes: true })
      for (const entry of entries) {
        if (entry.isDirectory()) {
          const skillMd = join(skillsDir, entry.name, 'SKILL.md')
          if (existsSync(skillMd)) {
            results.push({
              packageName: pkg,
              skillName: entry.name,
              sourcePath: join(skillsDir, entry.name),
            })
          }
        }
      }
    } catch {
      // skip unreadable directories
    }
  }

  return results
}

function generateMcpJson(cwd: string): void {
  const pm = detectPackageManager(cwd)
  const { command, args } = getMcpCommand(pm)

  const config = {
    mcpServers: {
      'rudderjs-boost': { command, args },
    },
  }

  const filePath = join(cwd, '.mcp.json')
  writeFileSync(filePath, JSON.stringify(config, null, 2) + '\n', 'utf-8')
  console.log('  Created .mcp.json')
}

function generateClaudeMd(cwd: string, guidelines: PackageGuideline[]): void {
  const filePath = join(cwd, 'CLAUDE.md')

  if (existsSync(filePath)) {
    console.log('  Skipped CLAUDE.md (already exists)')
    return
  }

  let content: string

  if (guidelines.length > 0) {
    const sections = guidelines.map(
      (g) => `## ${g.packageName}\n\n${g.content.trim()}`
    )
    content = `# CLAUDE.md\n\nAuto-generated by \`boost:install\`. Per-package guidelines from installed @rudderjs/* packages.\n\n${sections.join('\n\n---\n\n')}\n`
  } else {
    content = `# CLAUDE.md\n\nAuto-generated by \`boost:install\`.\n\nThis is a RudderJS project — a Laravel-inspired Node.js meta-framework.\nSee https://github.com/rudderjs/rudder for documentation.\n`
  }

  writeFileSync(filePath, content, 'utf-8')
  console.log('  Created CLAUDE.md')
}

function generateGuidelines(cwd: string, guidelines: PackageGuideline[]): void {
  if (guidelines.length === 0) return

  const dir = join(cwd, '.ai', 'guidelines')
  mkdirSync(dir, { recursive: true })

  for (const g of guidelines) {
    const dest = join(dir, `${g.shortName}.md`)
    writeFileSync(dest, g.content, 'utf-8')
    console.log(`  Created .ai/guidelines/${g.shortName}.md`)
  }
}

function generateSkills(cwd: string, skills: PackageSkill[]): void {
  if (skills.length === 0) return

  const dir = join(cwd, '.ai', 'skills')
  mkdirSync(dir, { recursive: true })

  for (const s of skills) {
    const dest = join(dir, s.skillName)
    cpSync(s.sourcePath, dest, { recursive: true })
    console.log(`  Created .ai/skills/${s.skillName}/`)
  }
}

function generateBoostJson(cwd: string, packages: string[]): void {
  const config = {
    version: '0.0.1',
    packages,
    generatedAt: new Date().toISOString(),
  }

  const filePath = join(cwd, 'boost.json')
  writeFileSync(filePath, JSON.stringify(config, null, 2) + '\n', 'utf-8')
  console.log('  Created boost.json')
}

export async function boostInstall(cwd: string): Promise<void> {
  console.log('\nBoost: Installing IDE configs for AI coding assistants...\n')

  const packages = findRudderPackages(cwd)
  if (packages.length === 0) {
    console.log('  No @rudderjs/* packages found in package.json.')
    return
  }

  console.log(`  Found ${packages.length} @rudderjs/* package(s): ${packages.join(', ')}\n`)

  const guidelines = collectGuidelines(cwd, packages)
  const skills = collectSkills(cwd, packages)

  generateMcpJson(cwd)
  generateClaudeMd(cwd, guidelines)
  generateGuidelines(cwd, guidelines)
  generateSkills(cwd, skills)
  generateBoostJson(cwd, packages)

  console.log('\nDone.\n')
}
